#!/bin/bash
# Read-only drift check for the Visual Studio build. Two solutions build the same agent and differ
# only in toolset: MeshAgent-2022.sln (v145 by default, v143 with /p:MeshToolset=v143) and MeshAgent-2019.sln (v142). The shared source list
# lives in MeshAgent.Common.props while the .filters files that group it for Solution Explorer sit
# next to each project, so the two drift apart silently. Nothing here builds or edits anything.

cd "$(dirname "$(readlink -f "$0")")" || exit 1

rc=0
fail() { echo "  FAIL: $*" >&2; rc=1; }
ok()   { echo "  ok:   $*"; }

SLN_2022=MeshAgent-2022.sln
SLN_2019=MeshAgent-2019.sln
PRJ_2022="meshconsole/MeshConsole-2022.vcxproj meshservice/MeshService-2022.vcxproj"
PRJ_2019="meshconsole/MeshConsole-2019.vcxproj meshservice/MeshService-2019.vcxproj"
ALL_PROJECTS="$PRJ_2022 $PRJ_2019"
# Generated by the pre-build event, so it is absent until the first build.
GENERATED="microscript/ILibDuktape_Commit.h"

# Prints "<kind> <path>" for every source item in an msbuild file. Paths in the shared props are
# relative to the importing project, so the base is always the project directory.
items() {
    python3 - "$1" "$2" <<'PY'
import os, sys, xml.etree.ElementTree as ET
path, base = sys.argv[1], sys.argv[2]
ns = '{http://schemas.microsoft.com/developer/msbuild/2003}'
for el in ET.parse(path).getroot().iter():
    kind = el.tag[len(ns):] if el.tag.startswith(ns) else el.tag
    if kind not in ('ClCompile', 'ClInclude', 'ResourceCompile', 'Image'):
        continue
    inc = el.get('Include')
    if not inc:
        continue
    print(kind, os.path.normpath(os.path.join(base, inc.replace('\\', '/'))))
PY
}

echo "== 1. each solution points at projects that exist ==========================="
for sln_prjs in "$SLN_2022|$PRJ_2022" "$SLN_2019|$PRJ_2019"; do
    sln=${sln_prjs%%|*}
    [ -f "$sln" ] || { fail "$sln is missing"; continue; }
    for p in ${sln_prjs#*|}; do
        grep -q "$(basename "$p")" "$sln" && ok "$sln references $p" || fail "$sln does not reference $p"
        [ -f "$p" ] || fail "$p is missing"
    done
done

echo "== 2. every .filters lists exactly the items its project builds ============"
for p in $ALL_PROJECTS; do
    f="$p.filters"
    [ -f "$f" ] || { fail "$f is missing"; continue; }
    dir=$(dirname "$p")
    built=$( { items "$p" "$dir"; items MeshAgent.Common.props "$dir"; } | sort -u)
    filed=$(items "$f" "$dir" | sort -u)
    miss=$(comm -23 <(echo "$built") <(echo "$filed"))
    extra=$(comm -13 <(echo "$built") <(echo "$filed"))
    [ -z "$miss" ]  || fail "$f does not file: $(echo "$miss" | tr '\n' ' ')"
    [ -z "$extra" ] || fail "$f files items nothing builds: $(echo "$extra" | tr '\n' ' ')"
    [ -n "$miss$extra" ] || ok "$f agrees with $p and MeshAgent.Common.props"
done

echo "== 3. every referenced source exists ======================================="
missing=""
for p in $ALL_PROJECTS; do
    dir=$(dirname "$p")
    for src in $( { items "$p" "$dir"; items MeshAgent.Common.props "$dir"; } | awk '{print $2}' | sort -u); do
        [ "$src" = "$GENERATED" ] && continue
        [ -f "$src" ] || missing="$missing $src"
    done
done
[ -z "$missing" ] && ok "every ClCompile/ClInclude/ResourceCompile/Image path resolves"                   || fail "referenced but not on disk:$missing"

echo "== 4. project and solution configurations agree ============================"
for sln_prjs in "$SLN_2022|$PRJ_2022" "$SLN_2019|$PRJ_2019"; do
    sln=${sln_prjs%%|*}
    [ -f "$sln" ] || continue
    sln_cfgs=$(sed -n 's/^\t\t\(.*\) = \1\r*$/\1/p' "$sln" | sed 's/|x86/|Win32/' | sort -u)
    for p in ${sln_prjs#*|}; do
        [ -f "$p" ] || continue
        prj_cfgs=$(grep -o 'ProjectConfiguration Include="[^"]*"' "$p" | sed 's/.*"\(.*\)"/\1/' | sort -u)
        if [ "$sln_cfgs" = "$prj_cfgs" ]; then
            ok "$p offers exactly the configurations in $sln"
        else
            fail "$p configurations differ from $sln: $(comm -3 <(echo "$sln_cfgs") <(echo "$prj_cfgs") | tr -s '\n\t' ' ')"
        fi
    done
done

echo "== 5. the -2019 and -2022 projects build the same sources =================="
# They exist only to differ in toolset, so a source added to one and not the other is a mistake.
for pair in meshconsole/MeshConsole meshservice/MeshService; do
    a="$pair-2022.vcxproj"; b="$pair-2019.vcxproj"
    dir=$(dirname "$pair")
    if [ -f "$a" ] && [ -f "$b" ]; then
        d=$(diff <(items "$a" "$dir" | sort -u) <(items "$b" "$dir" | sort -u))
        [ -z "$d" ] && ok "$b builds the same items as $a" \
                    || fail "$b and $a disagree: $(echo "$d" | tr -s '\n' ' ')"
    else
        fail "$a or $b is missing"
    fi
done

exit $rc
