#!/bin/sh
#
# Copy and run this in the OpenSSL directory for x86 Galileo compatible OpenSSL stack
#
# No WSL Debian3 substitute available - targets uclibc (see -uclibc suffix
# below); Debian's apt has no uclibc cross toolchain, glibc only.
export PATH=/home/default/Public/Galileo/arduino-1.5.3/hardware/tools/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux-uclibc/:$PATH
export CC="/home/default/Public/Galileo/arduino-1.5.3/hardware/tools/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux-uclibc/i586-poky-linux-uclibc-gcc --sysroot=/home/default/Public/Galileo/arduino-1.5.3/hardware/tools/sysroots/i586-poky-linux-uclibc"

cd ../openssl
make clean
./Configure linux-generic32 no-weak-ssl-ciphers no-srp no-psk no-comp no-zlib no-zlib-dynamic no-hw no-dso no-shared -no-asm no-rc5 no-idea no-md4 no-rmd160 no-ssl no-ssl3 no-seed no-camellia no-bf no-cast no-md2 no-mdc2 no-engine no-ocsp no-cms -Os -m32
make depend
make -j "$(nproc)"
mkdir -p ../linux/poky
cp *.a ../linux/poky
cd ..
