#!/bin/sh
#
# Copy and run this in the OpenSSL directory for ARM Pogoplug compatible OpenSSL stack
#
export CC=arm-linux-gnueabi-gcc

cd ../openssl
make clean
./Configure linux-generic32 no-weak-ssl-ciphers no-srp no-psk no-comp no-zlib no-zlib-dynamic no-hw no-dso no-shared -no-asm no-rc5 no-idea no-md4 no-rmd160 no-ssl no-ssl3 no-seed no-camellia no-bf no-cast no-md2 no-mdc2 no-engine no-ocsp no-cms -Os
make depend
make -j "$(nproc)"
mkdir -p ../linux/pogo
cp *.a ../linux/pogo
cd ..
